export interface CategoryTaxonomyEntry {
  primary: string;
  detailed: string;
}

/**
 * Default category taxonomy (16 primary, ~100 detailed), originally sourced
 * from Plaid's Personal Finance Category taxonomy. Kept as the app's own
 * taxonomy regardless of sync provider — it's a reasonable default category
 * set for user-driven categorization even when a provider supplies none.
 */
export const DEFAULT_CATEGORY_TAXONOMY: CategoryTaxonomyEntry[] = [
  { primary: 'INCOME', detailed: 'INCOME_DIVIDENDS' },
  { primary: 'INCOME', detailed: 'INCOME_INTEREST_EARNED' },
  { primary: 'INCOME', detailed: 'INCOME_RETIREMENT_PENSION' },
  { primary: 'INCOME', detailed: 'INCOME_TAX_REFUND' },
  { primary: 'INCOME', detailed: 'INCOME_UNEMPLOYMENT' },
  { primary: 'INCOME', detailed: 'INCOME_WAGES' },
  { primary: 'INCOME', detailed: 'INCOME_OTHER_INCOME' },
  { primary: 'TRANSFER_IN', detailed: 'TRANSFER_IN_CASH_ADVANCES_AND_LOANS' },
  { primary: 'TRANSFER_IN', detailed: 'TRANSFER_IN_DEPOSIT' },
  { primary: 'TRANSFER_IN', detailed: 'TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS' },
  { primary: 'TRANSFER_IN', detailed: 'TRANSFER_IN_SAVINGS' },
  { primary: 'TRANSFER_IN', detailed: 'TRANSFER_IN_ACCOUNT_TRANSFER' },
  { primary: 'TRANSFER_IN', detailed: 'TRANSFER_IN_OTHER_TRANSFER_IN' },
  { primary: 'TRANSFER_OUT', detailed: 'TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS' },
  { primary: 'TRANSFER_OUT', detailed: 'TRANSFER_OUT_SAVINGS' },
  { primary: 'TRANSFER_OUT', detailed: 'TRANSFER_OUT_WITHDRAWAL' },
  { primary: 'TRANSFER_OUT', detailed: 'TRANSFER_OUT_ACCOUNT_TRANSFER' },
  { primary: 'TRANSFER_OUT', detailed: 'TRANSFER_OUT_OTHER_TRANSFER_OUT' },
  { primary: 'LOAN_PAYMENTS', detailed: 'LOAN_PAYMENTS_CAR_PAYMENT' },
  { primary: 'LOAN_PAYMENTS', detailed: 'LOAN_PAYMENTS_CREDIT_CARD_PAYMENT' },
  { primary: 'LOAN_PAYMENTS', detailed: 'LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT' },
  { primary: 'LOAN_PAYMENTS', detailed: 'LOAN_PAYMENTS_MORTGAGE_PAYMENT' },
  { primary: 'LOAN_PAYMENTS', detailed: 'LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT' },
  { primary: 'LOAN_PAYMENTS', detailed: 'LOAN_PAYMENTS_OTHER_PAYMENT' },
  { primary: 'BANK_FEES', detailed: 'BANK_FEES_ATM_FEES' },
  { primary: 'BANK_FEES', detailed: 'BANK_FEES_FOREIGN_TRANSACTION_FEES' },
  { primary: 'BANK_FEES', detailed: 'BANK_FEES_INSUFFICIENT_FUNDS' },
  { primary: 'BANK_FEES', detailed: 'BANK_FEES_INTEREST_CHARGE' },
  { primary: 'BANK_FEES', detailed: 'BANK_FEES_OVERDRAFT_FEES' },
  { primary: 'BANK_FEES', detailed: 'BANK_FEES_OTHER_BANK_FEES' },
  { primary: 'ENTERTAINMENT', detailed: 'ENTERTAINMENT_CASINOS_AND_GAMBLING' },
  { primary: 'ENTERTAINMENT', detailed: 'ENTERTAINMENT_MUSIC_AND_AUDIO' },
  { primary: 'ENTERTAINMENT', detailed: 'ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS' },
  { primary: 'ENTERTAINMENT', detailed: 'ENTERTAINMENT_TV_AND_MOVIES' },
  { primary: 'ENTERTAINMENT', detailed: 'ENTERTAINMENT_VIDEO_GAMES' },
  { primary: 'ENTERTAINMENT', detailed: 'ENTERTAINMENT_OTHER_ENTERTAINMENT' },
  { primary: 'FOOD_AND_DRINK', detailed: 'FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR' },
  { primary: 'FOOD_AND_DRINK', detailed: 'FOOD_AND_DRINK_COFFEE' },
  { primary: 'FOOD_AND_DRINK', detailed: 'FOOD_AND_DRINK_FAST_FOOD' },
  { primary: 'FOOD_AND_DRINK', detailed: 'FOOD_AND_DRINK_GROCERIES' },
  { primary: 'FOOD_AND_DRINK', detailed: 'FOOD_AND_DRINK_RESTAURANT' },
  { primary: 'FOOD_AND_DRINK', detailed: 'FOOD_AND_DRINK_VENDING_MACHINES' },
  { primary: 'FOOD_AND_DRINK', detailed: 'FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK' },
  { primary: 'GENERAL_MERCHANDISE', detailed: 'GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS' },
  { primary: 'GENERAL_MERCHANDISE', detailed: 'GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES' },
  { primary: 'GENERAL_MERCHANDISE', detailed: 'GENERAL_MERCHANDISE_CONVENIENCE_STORES' },
  { primary: 'GENERAL_MERCHANDISE', detailed: 'GENERAL_MERCHANDISE_DEPARTMENT_STORES' },
  { primary: 'GENERAL_MERCHANDISE', detailed: 'GENERAL_MERCHANDISE_DISCOUNT_STORES' },
  { primary: 'GENERAL_MERCHANDISE', detailed: 'GENERAL_MERCHANDISE_ELECTRONICS' },
  { primary: 'GENERAL_MERCHANDISE', detailed: 'GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES' },
  { primary: 'GENERAL_MERCHANDISE', detailed: 'GENERAL_MERCHANDISE_OFFICE_SUPPLIES' },
  { primary: 'GENERAL_MERCHANDISE', detailed: 'GENERAL_MERCHANDISE_ONLINE_MARKETPLACES' },
  { primary: 'GENERAL_MERCHANDISE', detailed: 'GENERAL_MERCHANDISE_PET_SUPPLIES' },
  { primary: 'GENERAL_MERCHANDISE', detailed: 'GENERAL_MERCHANDISE_SPORTING_GOODS' },
  { primary: 'GENERAL_MERCHANDISE', detailed: 'GENERAL_MERCHANDISE_SUPERSTORES' },
  { primary: 'GENERAL_MERCHANDISE', detailed: 'GENERAL_MERCHANDISE_TOBACCO_AND_VAPE' },
  { primary: 'GENERAL_MERCHANDISE', detailed: 'GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE' },
  { primary: 'HOME_IMPROVEMENT', detailed: 'HOME_IMPROVEMENT_FURNITURE' },
  { primary: 'HOME_IMPROVEMENT', detailed: 'HOME_IMPROVEMENT_HARDWARE' },
  { primary: 'HOME_IMPROVEMENT', detailed: 'HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE' },
  { primary: 'HOME_IMPROVEMENT', detailed: 'HOME_IMPROVEMENT_SECURITY' },
  { primary: 'HOME_IMPROVEMENT', detailed: 'HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT' },
  { primary: 'MEDICAL', detailed: 'MEDICAL_DENTAL_CARE' },
  { primary: 'MEDICAL', detailed: 'MEDICAL_EYE_CARE' },
  { primary: 'MEDICAL', detailed: 'MEDICAL_NURSING_CARE' },
  { primary: 'MEDICAL', detailed: 'MEDICAL_PHARMACIES_AND_SUPPLEMENTS' },
  { primary: 'MEDICAL', detailed: 'MEDICAL_PRIMARY_CARE' },
  { primary: 'MEDICAL', detailed: 'MEDICAL_VETERINARY_SERVICES' },
  { primary: 'MEDICAL', detailed: 'MEDICAL_OTHER_MEDICAL' },
  { primary: 'PERSONAL_CARE', detailed: 'PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS' },
  { primary: 'PERSONAL_CARE', detailed: 'PERSONAL_CARE_HAIR_AND_BEAUTY' },
  { primary: 'PERSONAL_CARE', detailed: 'PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING' },
  { primary: 'PERSONAL_CARE', detailed: 'PERSONAL_CARE_OTHER_PERSONAL_CARE' },
  { primary: 'GENERAL_SERVICES', detailed: 'GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING' },
  { primary: 'GENERAL_SERVICES', detailed: 'GENERAL_SERVICES_AUTOMOTIVE' },
  { primary: 'GENERAL_SERVICES', detailed: 'GENERAL_SERVICES_CHILDCARE' },
  { primary: 'GENERAL_SERVICES', detailed: 'GENERAL_SERVICES_CONSULTING_AND_LEGAL' },
  { primary: 'GENERAL_SERVICES', detailed: 'GENERAL_SERVICES_EDUCATION' },
  { primary: 'GENERAL_SERVICES', detailed: 'GENERAL_SERVICES_INSURANCE' },
  { primary: 'GENERAL_SERVICES', detailed: 'GENERAL_SERVICES_POSTAGE_AND_SHIPPING' },
  { primary: 'GENERAL_SERVICES', detailed: 'GENERAL_SERVICES_STORAGE' },
  { primary: 'GENERAL_SERVICES', detailed: 'GENERAL_SERVICES_OTHER_GENERAL_SERVICES' },
  { primary: 'GOVERNMENT_AND_NON_PROFIT', detailed: 'GOVERNMENT_AND_NON_PROFIT_DONATIONS' },
  { primary: 'GOVERNMENT_AND_NON_PROFIT', detailed: 'GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES' },
  { primary: 'GOVERNMENT_AND_NON_PROFIT', detailed: 'GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT' },
  { primary: 'GOVERNMENT_AND_NON_PROFIT', detailed: 'GOVERNMENT_AND_NON_PROFIT_OTHER_GOVERNMENT_AND_NON_PROFIT' },
  { primary: 'TRANSPORTATION', detailed: 'TRANSPORTATION_BIKES_AND_SCOOTERS' },
  { primary: 'TRANSPORTATION', detailed: 'TRANSPORTATION_GAS' },
  { primary: 'TRANSPORTATION', detailed: 'TRANSPORTATION_PARKING' },
  { primary: 'TRANSPORTATION', detailed: 'TRANSPORTATION_PUBLIC_TRANSIT' },
  { primary: 'TRANSPORTATION', detailed: 'TRANSPORTATION_TAXIS_AND_RIDE_SHARES' },
  { primary: 'TRANSPORTATION', detailed: 'TRANSPORTATION_TOLLS' },
  { primary: 'TRANSPORTATION', detailed: 'TRANSPORTATION_OTHER_TRANSPORTATION' },
  { primary: 'TRAVEL', detailed: 'TRAVEL_FLIGHTS' },
  { primary: 'TRAVEL', detailed: 'TRAVEL_LODGING' },
  { primary: 'TRAVEL', detailed: 'TRAVEL_RENTAL_CARS' },
  { primary: 'TRAVEL', detailed: 'TRAVEL_OTHER_TRAVEL' },
  { primary: 'RENT_AND_UTILITIES', detailed: 'RENT_AND_UTILITIES_GAS_AND_ELECTRICITY' },
  { primary: 'RENT_AND_UTILITIES', detailed: 'RENT_AND_UTILITIES_INTERNET_AND_CABLE' },
  { primary: 'RENT_AND_UTILITIES', detailed: 'RENT_AND_UTILITIES_RENT' },
  { primary: 'RENT_AND_UTILITIES', detailed: 'RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT' },
  { primary: 'RENT_AND_UTILITIES', detailed: 'RENT_AND_UTILITIES_TELEPHONE' },
  { primary: 'RENT_AND_UTILITIES', detailed: 'RENT_AND_UTILITIES_WATER' },
  { primary: 'RENT_AND_UTILITIES', detailed: 'RENT_AND_UTILITIES_OTHER_UTILITIES' },
];
